---
title: "Different Bacteria found on the Screens of Cellphones of Students vs. Professors"
author: "Shreya Barma"
date: "8/27/2019"
output: word_document
csl: bioinformatics.csl
bibliography: references.bib 
---

# Overview of Project 

The project I am looking at will look at the different bacteria on different cell phone screens and classroom landlines. This is to see whether or not phones carry potential pathogens or disease-causing bacteria. Thus, this experiment can help build a correlation between how illnesses are spread and technology usage.I will specifically focus on the presence of E.Coli, Staphylococcus, and Pseudomonas.

This has been shown through studies in the past with teenagers and their cell phones, "We found a high median bacterial count on secondary school students’ mobile phones...and a median of 17,032 bacterial 16S rRNA gene copies per phone. Potentially pathogenic microbes were found among dominant microbes more often on phones with higher percentage of E. faecalis in total bacterial 16S rRNA" [@cogprints6566]. 

Furthermore, another study proved that there is an extremely high amount of bacteria on cellphones. "In total, 94.5% of phones demonstrated evidence of bacterial contamination with different types of bacteria...S. aureus strains isolated from mobile phones of 52% and those strains isolated from hands of 37.7% were methicillin resistant" [@ulger2009we]

# Question

"Do cellphones really carry potential pathogens? Does age play a factor in cellphone hygeine? " 

# Hypothesis 

All cellphones will carry potential pathogens. Student cellphones will have a significantly higher amount of potential pathogens compared to professor cellphones. 

# Study Design

For my sample set I will collect swabs from 4 students' cellphones and also collect swabs from 4 teachers. These students will be my 3 housemates and myself, and the professors will be from the classes I am currently taking. Once I have completed collecting my sample sets, I will extract DNA and culture the bacteria, identify specific types of bacteria I am focusing the study on, and run PCR's. 

## Materials Needed 

sterile swabs 
sterile tubes 
sterile buffer inside 